landscapeMemberClasses:
  - name: Premier Membership
    category: Premier
  - name: General Membership
    category: General
  - name: Associate Membership
    category: Associate
slug: openssf 
landscapeMemberCategory: OpenSSF Members
