name: Build Landscape from LFX

on:
  workflow_dispatch:
  schedule:
  - cron: "0 13 * * *"

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit
      - uses: jmertic/lfx-landscape-tools@main
        with:
          project_processing: skip
        env:
          token: ${{ secrets.PAT }}
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
